In [2]:
import uproot as up
from numpy import *
import scipy as sp
from scipy.optimize import curve_fit
from scipy.stats import chi2
from matplotlib.pyplot import *
from ROOT import TCanvas, TGraph, TH1F,TFile, TF1, gStyle, TH1D

Welcome to JupyROOT 6.24/00


In [3]:
file = up.open("/home/kuanyu/CMS/ZtoLL_Plot/ana/ee/cut_optimize/top/ee_Top_emjet_half.root")

In [4]:
file["Top_bjet_fakeRate"].member("fName")

'Top_bjet_fakeRate'

In [5]:
file["Top_bjet_fakeRate"].values()

array([ 0.0000000e+00,  5.6926626e-01,  3.7740618e-01,  3.0531123e-01,
        2.4599889e-01,  1.9625470e-01,  1.5318944e-01,  1.1857069e-01,
        9.4912045e-02,  7.2369583e-02,  5.2584216e-02,  4.1071031e-02,
        3.1191565e-02,  2.0434190e-02,  1.5691187e-02,  1.4822576e-02,
        9.1722803e-03,  8.7026330e-03,  4.9185073e-03,  2.0974677e-03,
        1.0793440e-03,  3.3879415e-03,  2.6297271e-03,  1.0728144e-04,
        5.1969234e-03,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
       -0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -0.0000000e+00,
        0.0000000e+00, -0.0000000e+00], dtype=float32)

In [6]:
def func_b(x,*par):
    return exp(par[0]+par[1]*x+par[2]*x*x) + par[3] * x +  par[4]

In [23]:
def func_c(x,*par):
    return exp(par[0]+par[1]*x) + par[2] * x +  par[3]

In [7]:
xdata = file["Top_bjet_fakeRate"].axis().edges()[1:-26]
ydata = file["Top_bjet_fakeRate"].values()[1:-25]
ydata

array([5.6926626e-01, 3.7740618e-01, 3.0531123e-01, 2.4599889e-01,
       1.9625470e-01, 1.5318944e-01, 1.1857069e-01, 9.4912045e-02,
       7.2369583e-02, 5.2584216e-02, 4.1071031e-02, 3.1191565e-02,
       2.0434190e-02, 1.5691187e-02, 1.4822576e-02, 9.1722803e-03,
       8.7026330e-03, 4.9185073e-03, 2.0974677e-03, 1.0793440e-03,
       3.3879415e-03, 2.6297271e-03, 1.0728144e-04, 5.1969234e-03],
      dtype=float32)

In [8]:
popt = zeros(5)  
popt, pcov = curve_fit(func_b, xdata, ydata, p0 = popt, maxfev = 120000, bounds = [-1,1])

In [9]:
for i in range(len(popt)):
    print(f"par{i} = {popt[i]}")

par0 = -0.31213349853753525
par1 = -0.3369597634649318
par2 = 0.01007077697094194
par3 = -0.003960699254309169
par4 = 0.0291339908830591


In [11]:
# Calculate chi Squared
f_opti = func_b(xdata,*popt)
ch2_opti = np.sum( (ydata-f_opti)**2/ydata)
# Calculate Degrees of Freedom with 5 fit parameters
lenx = len(xdata)
dof = lenx-len(popt)
Chi2_dof = str(ch2_opti/dof)
print(Chi2_dof)
print('Hist\tCalc Package\tChi Sq\t Chi2/dof')
print('SciPy\tPython\t{0}\t{1}'.format(ch2_opti, ch2_opti/dof))

0.0057862296089215256
Hist	Calc Package	Chi Sq	 Chi2/dof
SciPy	Python	0.10993836256950898	0.0057862296089215256


In [10]:
%matplotlib qt
figure()
title("Top b fake rate")
ylabel("fake rate")
xlabel("Jet track multiplicity")
x_major_locator=MultipleLocator(1)
original_data, = plot(xdata, ydata,"x")
fitcurve_data, = plot(xdata, func_b(xdata,*popt))
text, = plot(0,0,"white")
l1 = legend([original_data,fitcurve_data],["Top b fake rate","fitting curve"],loc = 'upper right')
figure()
#title(" data / fit result")
# plot(testx, testy)
#plot(testx, testy/func(testx,*popt))
ydata

array([5.6926626e-01, 3.7740618e-01, 3.0531123e-01, 2.4599889e-01,
       1.9625470e-01, 1.5318944e-01, 1.1857069e-01, 9.4912045e-02,
       7.2369583e-02, 5.2584216e-02, 4.1071031e-02, 3.1191565e-02,
       2.0434190e-02, 1.5691187e-02, 1.4822576e-02, 9.1722803e-03,
       8.7026330e-03, 4.9185073e-03, 2.0974677e-03, 1.0793440e-03,
       3.3879415e-03, 2.6297271e-03, 1.0728144e-04, 5.1969234e-03],
      dtype=float32)

qt.qpa.gl: QXcbConnection: Failed to initialize GLX
libEGL warning: DRI3: failed to query the version
libEGL warning: DRI2: failed to authenticate
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 407, resource id: 384, major code: 139 (Unknown), minor code: 1


In [12]:
file["Top_cjet_fakeRate"].member("fName")

'Top_cjet_fakeRate'

In [13]:
file["Top_cjet_fakeRate"].values()

array([ 0.0000000e+00,  3.5072583e-01,  1.4851704e-01,  9.1632336e-02,
        6.0634229e-02,  3.0721340e-02,  1.7946236e-02,  8.6834114e-03,
        6.1223335e-03,  9.4551705e-03,  2.2701472e-03,  4.0948461e-03,
        2.7139315e-03,  3.4335867e-04,  1.2096359e-04,  8.2050326e-05,
        4.1158142e-04,  4.3082717e-03, -1.8899479e-04,  0.0000000e+00,
        5.2919507e-04,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
       -0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00], dtype=float32)

In [17]:
xdata = file["Top_cjet_fakeRate"].axis().edges()[1:-32]
ydata = file["Top_cjet_fakeRate"].values()[1:-31]
ydata

array([ 3.5072583e-01,  1.4851704e-01,  9.1632336e-02,  6.0634229e-02,
        3.0721340e-02,  1.7946236e-02,  8.6834114e-03,  6.1223335e-03,
        9.4551705e-03,  2.2701472e-03,  4.0948461e-03,  2.7139315e-03,
        3.4335867e-04,  1.2096359e-04,  8.2050326e-05,  4.1158142e-04,
        4.3082717e-03, -1.8899479e-04], dtype=float32)

In [24]:
popt = zeros(4)  
popt, pcov = curve_fit(func_c, xdata, ydata, p0 = popt, maxfev = 120000, bounds = [-1,1])

In [25]:
for i in range(len(popt)):
    print(f"par{i} = {popt[i]}")

par0 = -0.3248291488513345
par1 = -0.7911177718871826
par2 = -0.0012678123101242413
par3 = 0.01978378986710919


In [27]:
# Calculate chi Squared
f_opti = func_c(xdata,*popt)
ch2_opti = np.sum( (ydata-f_opti)**2/ydata)
# Calculate Degrees of Freedom with 5 fit parameters
lenx = len(xdata)
dof = lenx-len(popt)
Chi2_dof = str(ch2_opti/dof)
print(Chi2_dof)
print('Hist\tCalc Package\tChi Sq\t Chi2/dof')
print('SciPy\tPython\t{0}\t{1}'.format(ch2_opti, ch2_opti/dof))

0.004112417660806254
Hist	Calc Package	Chi Sq	 Chi2/dof
SciPy	Python	0.05757384725128755	0.004112417660806254


In [31]:
%matplotlib qt
figure()
title("Top c fake rate")
ylabel("fake rate")
xlabel("Jet track multiplicity")
x_major_locator=MultipleLocator(1)
original_data, = plot(xdata, ydata,"x")
fitcurve_data, = plot(xdata, func_c(xdata,*popt))
text, = plot(0,0,"white")
l1 = legend([original_data,fitcurve_data],["Top c fake rate","fitting curve"],loc = 'upper right')
figure()
#title(" data / fit result")
# plot(testx, testy)
#plot(testx, testy/func(testx,*popt))
ydata

array([ 3.5072583e-01,  1.4851704e-01,  9.1632336e-02,  6.0634229e-02,
        3.0721340e-02,  1.7946236e-02,  8.6834114e-03,  6.1223335e-03,
        9.4551705e-03,  2.2701472e-03,  4.0948461e-03,  2.7139315e-03,
        3.4335867e-04,  1.2096359e-04,  8.2050326e-05,  4.1158142e-04,
        4.3082717e-03, -1.8899479e-04], dtype=float32)

In [32]:
file["Top_light_fakeRate"].member("fName")

'Top_light_fakeRate'

In [33]:
file["Top_light_fakeRate"].values()

array([ 0.0000000e+00,  4.5878190e-01,  2.4679099e-01,  1.3140407e-01,
        6.4531557e-02,  3.6118936e-02,  1.8966639e-02,  1.0530735e-02,
        5.3410428e-03,  3.8052590e-03,  2.3564715e-03,  1.8183951e-03,
        1.0321132e-03,  8.5489929e-04,  7.5348141e-04,  1.0192371e-03,
        1.5965397e-03,  4.7974542e-04, -4.0524690e-05,  5.3850261e-05,
        9.7683561e-04,  4.8749222e-05,  5.8759702e-05,  2.0974900e-03,
        0.0000000e+00,  0.0000000e+00,  1.7977122e-04,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00, -5.3015718e-04,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00, -0.0000000e+00], dtype=float32)

In [37]:
xdata = file["Top_light_fakeRate"].axis().edges()[1:-27]
ydata = file["Top_light_fakeRate"].values()[1:-26]
ydata

array([ 4.5878190e-01,  2.4679099e-01,  1.3140407e-01,  6.4531557e-02,
        3.6118936e-02,  1.8966639e-02,  1.0530735e-02,  5.3410428e-03,
        3.8052590e-03,  2.3564715e-03,  1.8183951e-03,  1.0321132e-03,
        8.5489929e-04,  7.5348141e-04,  1.0192371e-03,  1.5965397e-03,
        4.7974542e-04, -4.0524690e-05,  5.3850261e-05,  9.7683561e-04,
        4.8749222e-05,  5.8759702e-05,  2.0974900e-03], dtype=float32)

In [39]:
popt = zeros(5)  
popt, pcov = curve_fit(func_b, xdata, ydata, p0 = popt, maxfev = 120000, bounds = [-1,1])

In [40]:
for i in range(len(popt)):
    print(f"par{i} = {popt[i]}")

par0 = -0.1801414778747165
par1 = -0.5934543801756226
par2 = -0.010654744833624658
par3 = -9.762305271053515e-05
par4 = 0.0025466629971345888


In [45]:
f_opti = func_b(xdata,*popt)
ch2_opti = np.sum( (ydata-f_opti)**2/ydata)
# Calculate Degrees of Freedom with 5 fit parameters
lenx = len(xdata)
dof = lenx-len(popt)
Chi2_dof = str(ch2_opti/dof)
print(Chi2_dof)
print('Hist\tCalc Package\tChi Sq\t Chi2/dof')
print('SciPy\tPython\t{0}\t{1}'.format(ch2_opti, ch2_opti/dof))

2.6738851144411427e-06
Hist	Calc Package	Chi Sq	 Chi2/dof
SciPy	Python	4.812993205994057e-05	2.6738851144411427e-06


In [48]:
%matplotlib qt
figure()
title("Top light fake rate")
ylabel("fake rate")
xlabel("Jet track multiplicity")
x_major_locator=MultipleLocator(1)
original_data, = plot(xdata, ydata,"x")
fitcurve_data, = plot(xdata, func_b(xdata,*popt))
text, = plot(0,0,"white")
l1 = legend([original_data,fitcurve_data],["Top light fake rate","fitting curve"],loc = 'upper right')
figure()
#title(" data / fit result")
# plot(testx, testy)
#plot(testx, testy/func(testx,*popt))
ydata

array([ 4.5878190e-01,  2.4679099e-01,  1.3140407e-01,  6.4531557e-02,
        3.6118936e-02,  1.8966639e-02,  1.0530735e-02,  5.3410428e-03,
        3.8052590e-03,  2.3564715e-03,  1.8183951e-03,  1.0321132e-03,
        8.5489929e-04,  7.5348141e-04,  1.0192371e-03,  1.5965397e-03,
        4.7974542e-04, -4.0524690e-05,  5.3850261e-05,  9.7683561e-04,
        4.8749222e-05,  5.8759702e-05,  2.0974900e-03], dtype=float32)