In [1]:
import uproot as up
from numpy import *
import scipy as sp
from scipy.optimize import curve_fit
from scipy.stats import chi2
from matplotlib.pyplot import *
from ROOT import TCanvas, TGraph, TH1F,TFile, TF1, gStyle, TH1D

Welcome to JupyROOT 6.26/00


In [2]:
file = up.open("./../ee/cut_optimize/DY/ee_DY_emjet_half.root")

In [3]:
file["HT_light_fakeRate"].member("fName")

'HT_light_fakeRate'

In [4]:
file["HT_light_fakeRate"].axis().edges()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [5]:
file["HT_light_fakeRate"].values()

array([0.00000000e+00, 5.80480278e-01, 3.18238348e-01, 1.77361548e-01,
       1.01869635e-01, 6.10639863e-02, 3.55787016e-02, 2.24792976e-02,
       1.40164383e-02, 8.50702543e-03, 5.86515013e-03, 3.36765335e-03,
       1.80778711e-03, 1.68038381e-03, 1.28881773e-03, 9.57379758e-04,
       1.71738293e-03, 7.18061405e-04, 6.38553291e-04, 4.32211265e-04,
       4.43756056e-04, 4.68217826e-04, 1.38794407e-04, 1.82368822e-04,
       9.96344723e-04, 2.63656984e-04, 1.38558520e-04, 1.38150202e-03,
       1.24983359e-04, 1.62813711e-04, 1.26216750e-04, 4.20982280e-04,
       2.13678359e-04, 4.90248320e-04, 3.36757919e-04, 3.05018883e-04,
       5.46917785e-04, 7.13861897e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.30878492e-03,
       0.00000000e+00, 0.00000000e+00, 5.78248361e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00], dtype=float32)

In [6]:
def func_light(x,*par):
    return exp(par[0]+par[1]*x+par[2]*x*x) + par[3] * x +  par[4]

In [37]:
def func_c(x,*par):
    return exp(par[0]+par[1]*x+par[2]*x*x) + par[3] * x*x +  par[4]*x+ par[5]

In [94]:
def func_b(x,*par):
    return exp(par[0]+par[1]*x)+  par[2]*x+ par[3]

In [103]:
xdata = file["HT_light_fakeRate"].axis().edges()[1:-14]
ydata = file["HT_light_fakeRate"].values()[1:-13]
xdata

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36.])

In [9]:
ydata

array([5.80480278e-01, 3.18238348e-01, 1.77361548e-01, 1.01869635e-01,
       6.10639863e-02, 3.55787016e-02, 2.24792976e-02, 1.40164383e-02,
       8.50702543e-03, 5.86515013e-03, 3.36765335e-03, 1.80778711e-03,
       1.68038381e-03, 1.28881773e-03, 9.57379758e-04, 1.71738293e-03,
       7.18061405e-04, 6.38553291e-04, 4.32211265e-04, 4.43756056e-04,
       4.68217826e-04, 1.38794407e-04, 1.82368822e-04, 9.96344723e-04,
       2.63656984e-04, 1.38558520e-04, 1.38150202e-03, 1.24983359e-04,
       1.62813711e-04, 1.26216750e-04, 4.20982280e-04, 2.13678359e-04,
       4.90248320e-04, 3.36757919e-04, 3.05018883e-04, 5.46917785e-04],
      dtype=float32)

In [104]:
popt = zeros(5)  
popt, pcov = curve_fit(func_light, xdata, ydata, p0 = popt, maxfev = 120000, bounds = [-1,1])

In [105]:
for i in range(len(popt)):
    print(f"par{i} = {popt[i]}")

par0 = 0.08113296235574718
par1 = -0.6362062252254793
par2 = 0.011421667042199464
par3 = 1.1046894534748337e-05
par4 = -0.0001393183924009835


In [67]:
for i in range(len(popt)):
    print(f"par{i} = {popt[i]}")

par0 = 0.08118787223744216
par1 = -0.6362557021027739
par2 = 0.01143712998969338
par3 = 1.142707756756366e-05
par4 = -0.00014995176601499091


In [109]:
# Calculate chi Squared
f_opti = func_light(xdata,*popt)
ch2_opti = np.sum( (ydata-f_opti)**2/ydata)
# Calculate Degrees of Freedom with 5 fit parameters
lenx = len(xdata)
dof = lenx-len(popt)
Chi2_dof = str(ch2_opti/dof)
print(Chi2_dof)
print('Hist\tCalc Package\tChi Sq\t Chi2/dof')
print('SciPy\tPython\t{0}\t{1}'.format(ch2_opti, ch2_opti/dof))

0.0001384563241929822
Hist	Calc Package	Chi Sq	 Chi2/dof
SciPy	Python	0.004430602374175431	0.0001384563241929822


In [106]:
%matplotlib qt
figure()
title("Drell-Yan light fake rate")
ylabel("fake rate")
xlabel("Jet track multiplicity")
x_major_locator=MultipleLocator(1)
original_data, = plot(xdata, ydata,"x")
fitcurve_data, = plot(xdata, func_light(xdata,*popt))
text, = plot(0,0,"white")
l1 = legend([original_data,fitcurve_data],["Drell-Yan light fake rate","fitting curve"],loc = 'upper right')
#figure()
#title(" data / fit result")
# plot(testx, testy)
#plot(testx, testy/func(testx,*popt))
ydata

array([5.80480278e-01, 3.18238348e-01, 1.77361548e-01, 1.01869635e-01,
       6.10639863e-02, 3.55787016e-02, 2.24792976e-02, 1.40164383e-02,
       8.50702543e-03, 5.86515013e-03, 3.36765335e-03, 1.80778711e-03,
       1.68038381e-03, 1.28881773e-03, 9.57379758e-04, 1.71738293e-03,
       7.18061405e-04, 6.38553291e-04, 4.32211265e-04, 4.43756056e-04,
       4.68217826e-04, 1.38794407e-04, 1.82368822e-04, 9.96344723e-04,
       2.63656984e-04, 1.38558520e-04, 1.38150202e-03, 1.24983359e-04,
       1.62813711e-04, 1.26216750e-04, 4.20982280e-04, 2.13678359e-04,
       4.90248320e-04, 3.36757919e-04, 3.05018883e-04, 5.46917785e-04],
      dtype=float32)

In [111]:
file["HT_cjet_fakeRate"].member("fName")

'HT_cjet_fakeRate'

In [113]:
file["HT_cjet_fakeRate"].values()

array([0.0000000e+00, 3.9170370e-01, 1.6859736e-01, 8.8859290e-02,
       5.5571698e-02, 3.3747010e-02, 1.8293547e-02, 1.2556858e-02,
       9.0257218e-03, 6.2308582e-03, 4.8960820e-03, 2.8664437e-03,
       2.5033241e-03, 1.6508430e-03, 1.0444091e-03, 2.5604027e-03,
       1.1428441e-03, 4.1687026e-04, 8.4338844e-04, 1.5926908e-04,
       1.0101123e-04, 3.7824918e-04, 3.4863618e-04, 1.3485903e-04,
       1.6666502e-04, 1.5703557e-04, 1.9392524e-04, 3.7917891e-04,
       4.0242684e-04, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.2554912e-03,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3077877e-03,
       0.0000000e+00, 0.0000000e+00], dtype=float32)

In [112]:
file["HT_cjet_fakeRate"].axis().edges()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [62]:
cjet_data = file["HT_cjet_fakeRate"].axis().edges()[1:-1]
cjet_ydata = file["HT_cjet_fakeRate"].values()[1:]
cjet_ydata

array([3.9170370e-01, 1.6859736e-01, 8.8859290e-02, 5.5571698e-02,
       3.3747010e-02, 1.8293547e-02, 1.2556858e-02, 9.0257218e-03,
       6.2308582e-03, 4.8960820e-03, 2.8664437e-03, 2.5033241e-03,
       1.6508430e-03, 1.0444091e-03, 2.5604027e-03, 1.1428441e-03,
       4.1687026e-04, 8.4338844e-04, 1.5926908e-04, 1.0101123e-04,
       3.7824918e-04, 3.4863618e-04, 1.3485903e-04, 1.6666502e-04,
       1.5703557e-04, 1.9392524e-04, 3.7917891e-04, 4.0242684e-04,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 2.2554912e-03, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 1.3077877e-03, 0.0000000e+00,
       0.0000000e+00], dtype=float32)

In [83]:
popt = zeros(5)
popt, pcov = curve_fit(func_light, cjet_data, cjet_ydata, p0 = popt, maxfev = 120000, bounds = [-1,1])

In [84]:
# Calculate chi Squared
f_opti = func_light(cjet_data,*popt)
ch2_opti = np.sum( (cjet_ydata-f_opti)**2/cjet_ydata)
# Calculate Degrees of Freedom with 5 fit parameters
lenx = len(cjet_data)
dof = lenx-len(popt)
Chi2_dof = str(ch2_opti/dof)
print(Chi2_dof)
print('Hist\tCalc Package\tChi Sq\t Chi2/dof')
print('SciPy\tPython\t{0}\t{1}'.format(ch2_opti, ch2_opti/dof))

inf
Hist	Calc Package	Chi Sq	 Chi2/dof
SciPy	Python	inf	inf


<ipython-input-84-8d32a217e282>:3: RuntimeWarning: divide by zero encountered in true_divide
  ch2_opti = np.sum( (cjet_ydata-f_opti)**2/cjet_ydata)


In [90]:
%matplotlib qt
figure()
title("Drell-Yan c flavor fake rate")
ylabel("fake rate")
xlabel("Jet track multiplicity")
x_major_locator=MultipleLocator(1)
original_data, = plot(cjet_data, cjet_ydata,"x")
fitcurve_data, = plot(cjet_data, func_light(cjet_data,*popt))
text, = plot(0,0,"white")
l1 = legend([original_data,fitcurve_data],["Drell-Yan c fake rate","fitting curve"],loc = 'upper right')
figure()
title(" data / fit result")
#plot(cjet_data, cjet_ydata)
plot(cjet_data, cjet_ydata/func_light(cjet_data,*popt))
#ydata

In [87]:
for i in range(len(popt)):
    print(f"par{i} = {popt[i]}")

par0 = -0.155879619433122
par1 = -0.8197317704086138
par2 = 0.014493676237956263
par3 = -0.000158355043308647
par4 = 0.005435107513335813


In [91]:
file["HT_bjet_fakeRate"].member("fName")

'HT_bjet_fakeRate'

In [92]:
bjet_data = file["HT_bjet_fakeRate"].axis().edges()[1:-1]
bjet_ydata = file["HT_bjet_fakeRate"].values()[1:]
bjet_ydata

array([5.33097506e-01, 3.59892219e-01, 2.91233897e-01, 2.28263736e-01,
       1.86779261e-01, 1.36610538e-01, 1.12579130e-01, 9.41011161e-02,
       7.68224820e-02, 5.15174605e-02, 4.22011465e-02, 3.83251049e-02,
       3.36279050e-02, 2.17292476e-02, 1.12437978e-02, 1.44291315e-02,
       5.18629327e-03, 7.85818603e-03, 1.04402825e-02, 3.51918885e-03,
       4.98966454e-03, 5.29964280e-04, 1.20534305e-03, 6.37027842e-04,
       8.98129132e-04, 0.00000000e+00, 1.57468836e-03, 0.00000000e+00,
       0.00000000e+00], dtype=float32)

In [100]:
popt = zeros(5)
popt, pcov = curve_fit(func_light, bjet_data, bjet_ydata, p0 = popt, maxfev = 120000, bounds = [-1,1])

In [101]:
%matplotlib qt
figure()
title("Drell-Yan b flavor fake rate")
ylabel("fake rate")
xlabel("Jet track multiplicity")
x_major_locator=MultipleLocator(1)
original_data, = plot(bjet_data, bjet_ydata,"x")
fitcurve_data, = plot(bjet_data, func_light(bjet_data,*popt))
text, = plot(0,0,"white")
l1 = legend([original_data,fitcurve_data],["Drell-Yan b fake rate","fitting curve"],loc = 'upper right')
figure()
title(" data / fit result")
#plot(cjet_data, cjet_ydata)
plot(bjet_data, bjet_ydata/func_light(bjet_data,*popt))
#ydata

In [102]:
for i in range(len(popt)):
    print(f"par{i} = {popt[i]}")

par0 = -0.36929055060873117
par1 = -0.32227621971627424
par2 = 0.0077448118765263176
par3 = -0.0018266700500858249
par4 = 0.016124941879979406
